/**
 * Trade / marketplace cut & shape names (listing-style catalog).
 * Counts from marketplaces are omitted; values are stable slugs.
 */
export const GEM_CUTS = [
  { value: 'american', label: 'American' },
  { value: 'antique', label: 'Antique' },
  { value: 'asscher', label: 'Asscher' },
  { value: 'baguette', label: 'Baguette' },
  { value: 'baguette_cabochon', label: 'Baguette Cabochon' },
  { value: 'ball', label: 'Ball' },
  { value: 'barrel_shaped', label: 'Barrel-shaped' },
  { value: 'briolette', label: 'Briolette' },
  { value: 'bud', label: 'Bud' },
  { value: 'cabochon', label: 'Cabochon' },
  { value: 'carre', label: 'Carre' },
  { value: 'carved', label: 'Carved' },
  { value: 'ceylon', label: 'Ceylon' },
  { value: 'coat_of_arms', label: 'Coat-of-Arms' },
  { value: 'concave_cut', label: 'Concave Cut' },
  { value: 'concave_round', label: 'Concave Round' },
  { value: 'cushion', label: 'Cushion' },
  { value: 'cushion_antique_brilliant', label: 'Cushion Antique Brilliant' },
  { value: 'cushion_cabochon', label: 'Cushion Cabochon' },
  { value: 'double_brilliant', label: 'Double Brilliant' },
  { value: 'double_rose', label: 'Double Rose' },
  { value: 'drop', label: 'Drop' },
  { value: 'fan', label: 'Fan' },
  { value: 'fancy', label: 'Fancy' },
  { value: 'fancy_cabochon', label: 'Fancy Cabochon' },
  { value: 'flower_cut', label: 'Flower Cut' },
  { value: 'french', label: 'French' },
  { value: 'half_brilliant', label: 'Half-Brilliant' },
  { value: 'heart', label: 'Heart' },
  { value: 'heart_cabochon', label: 'Heart Cabochon' },
  { value: 'hexagon', label: 'Hexagon' },
  { value: 'hexagon_cabochon', label: 'Hexagon Cabochon' },
  { value: 'highlight_brilliant', label: 'Highlight Brilliant' },
  { value: 'jubilee', label: 'Jubilee' },
  { value: 'king', label: 'King' },
  { value: 'kite', label: 'Kite' },
  { value: 'magna', label: 'Magna' },
  { value: 'marquise_cabochon', label: 'Marquise Cabochon' },
  { value: 'mazarin', label: 'Mazarin' },
  { value: 'mixed', label: 'Mixed' },
  { value: 'navette', label: 'Navette' },
  { value: 'needle_brilliant', label: 'Needle Brilliant' },
  { value: 'net', label: 'Net' },
  { value: 'octagon', label: 'Octagon' },
  { value: 'octagon_cabochon', label: 'Octagon Cabochon' },
  { value: 'old_european', label: 'Old European' },
  { value: 'old_mine', label: 'Old Mine' },
  { value: 'old_single', label: 'Old Single' },
  { value: 'olive', label: 'Olive' },
  { value: 'oval', label: 'Oval' },
  { value: 'oval_cabochon', label: 'Oval Cabochon' },
  { value: 'oval_portuguese', label: 'Oval Portuguese' },
  { value: 'parallelogram', label: 'Parallelogram' },
  { value: 'pear_cabochon', label: 'Pear Cabochon' },
  { value: 'pendeloque', label: 'Pendeloque' },
  { value: 'pentagon', label: 'Pentagon' },
  { value: 'peruzzi', label: 'Peruzzi' },
  { value: 'petal', label: 'Petal' },
  { value: 'point', label: 'Point' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'portuguese_trillion', label: 'Portuguese Trillion' },
  { value: 'princess', label: 'Princess' },
  { value: 'radiant_cut', label: 'Radiant Cut' },
  { value: 'recoupe_rose', label: 'Recoupé-Rose' },
  { value: 'rhomb', label: 'Rhomb' },
  { value: 'rhomb_cabochon', label: 'Rhomb Cabochon' },
  { value: 'rose', label: 'Rose' },
  { value: 'round', label: 'Round' },
  { value: 'round_cabochon', label: 'Round Cabochon' },
  { value: 'shield', label: 'Shield' },
  { value: 'sphere', label: 'Sphere' },
  { value: 'square', label: 'Square' },
  { value: 'square_brilliant', label: 'Square Brilliant' },
  { value: 'square_cabochon', label: 'Square Cabochon' },
  { value: 'square_cushion', label: 'Square Cushion' },
  { value: 'star_brilliant', label: 'Star Brilliant' },
  { value: 'star_cut', label: 'Star cut' },
  { value: 'swiss', label: 'Swiss' },
  { value: 'table', label: 'Table' },
  { value: 'trapezoid', label: 'Trapezoid' },
  { value: 'triangle', label: 'Triangle' },
  { value: 'triangle_cut_corner', label: 'Triangle, cut-corner' },
  { value: 'trilliant', label: 'Trilliant' },
  { value: 'trillion', label: 'Trillion' },
  { value: 'trillion_cabochon', label: 'Trillion Cabochon' },
  { value: 'uncut', label: 'Uncut' },
  { value: 'whirl', label: 'Whirl' },
] as const;
