import { useQuery } from '@tanstack/react-query';
import * as WebBrowser from 'expo-web-browser';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';

import { PlaceField } from '@/components/flights/place-field';
import { BottomSheet } from '@/components/ui/bottom-sheet';
import { Icon } from '@/components/ui/icon';
import { StackHeader } from '@/components/ui/stack-header';
import { Radius, Spacing, Typography } from '@/constants/design-tokens';
import { airlineLogoUrl, createFlightBookingLink, formatFlightDateTime, formatFlightDuration, getFlightPriceCalendar, searchFlights, type FlightOffer, type FlightPlace, type FlightSearchCriteria } from '@/features/flights/flights-service';
import { useAppTheme } from '@/hooks/use-app-theme';
import { usePreferredCurrency } from '@/hooks/use-preferred-currency';
import { friendlyError } from '@/lib/errors';
import { haptics } from '@/lib/haptics';
import { useToast } from '@/providers/toast-provider';
import { Image } from 'expo-image';

function today() { return new Date().toISOString().slice(0, 10); }
function formatFare(value: number, currency: string) { return new Intl.NumberFormat('en', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value); }
function isDate(value: string) { return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(value).valueOf()); }

export default function FlightsScreen() {
  const { colors } = useAppTheme(); const toast = useToast(); const preferredCurrency = usePreferredCurrency();
  const [origin, setOrigin] = useState<FlightPlace | null>(null); const [destination, setDestination] = useState<FlightPlace | null>(null);
  const [departureAt, setDepartureAt] = useState(today); const [returnAt, setReturnAt] = useState(''); const [oneWay, setOneWay] = useState(true); const [direct, setDirect] = useState(false);
  const [sort, setSort] = useState<'price' | 'duration' | 'stops'>('price');
  const [criteria, setCriteria] = useState<FlightSearchCriteria | null>(null); const [selected, setSelected] = useState<FlightOffer | null>(null);
  const search = useQuery({ queryKey: ['flight-search', criteria], queryFn: () => searchFlights(criteria!), enabled: !!criteria, staleTime: 60_000, retry: 1 });
  const calendar = useQuery({ queryKey: ['flight-calendar', criteria], queryFn: () => getFlightPriceCalendar(criteria!), enabled: !!criteria, staleTime: 60_000, retry: 1 });
  const offers = useMemo(() => [...(search.data?.offers ?? [])].sort((a, b) => {
    if (sort === 'duration') return (a.duration ?? Number.MAX_SAFE_INTEGER) - (b.duration ?? Number.MAX_SAFE_INTEGER);
    if (sort === 'stops') return a.transfers - b.transfers || a.price - b.price;
    return a.price - b.price;
  }), [search.data, sort]);

  function submit() {
    if (!origin?.code || !destination?.code) { toast.error('Choose an origin and destination airport or city.'); return; }
    if (!isDate(departureAt) || (!oneWay && !isDate(returnAt))) { toast.error('Enter dates as YYYY-MM-DD.'); return; }
    if (!oneWay && returnAt < departureAt) { toast.error('Return date must be after departure.'); return; }
    haptics.commit(); setCriteria({ origin: origin.code, destination: destination.code, departureAt, ...(oneWay ? {} : { returnAt }), oneWay, direct, currency: preferredCurrency === 'RMB' ? 'CNY' : preferredCurrency, limit: 20, page: 1 });
  }
  async function openOffer(offer: FlightOffer) { if (!offer.bookingUrl) { toast.error('A booking link is unavailable for this cached fare.'); return; } try { const result = await createFlightBookingLink(offer.bookingUrl); await WebBrowser.openBrowserAsync(result.bookingUrl); } catch (error) { toast.error(friendlyError(error, 'Could not create your affiliate booking link.')); } }
  const error = search.error ? friendlyError(search.error, 'Could not load flight fares.') : null;

  return <View style={[styles.safe, { backgroundColor: colors.background }]}>
    <StackHeader title="Flights" />
    <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={search.isRefetching || calendar.isRefetching} onRefresh={() => { void search.refetch(); void calendar.refetch(); }} />}>
      <View style={[styles.hero, { backgroundColor: colors.primaryContainer }]}>
        <Icon name="travel-explore" size={26} color={colors.onPrimaryContainer} />
        <View style={{ flex: 1, gap: 2 }}><Text selectable style={[styles.heroTitle, { color: colors.onPrimaryContainer }]}>Flights for your next trip</Text><Text selectable style={[styles.heroCopy, { color: colors.onPrimaryContainer }]}>Explore Aviasales’ latest cached fares. Prices can change before booking.</Text></View>
      </View>
      <View style={[styles.panel, { backgroundColor: colors.surfaceContainerLowest, borderColor: colors.outlineVariant }]}>
        <PlaceField label="From" value={origin} onSelect={setOrigin} />
        <View style={{ alignItems: 'center' }}><Pressable accessibilityLabel="Swap origin and destination" onPress={haptics.wrap('selection', () => { setOrigin(destination); setDestination(origin); })} style={[styles.swap, { backgroundColor: colors.surfaceContainerHigh }]}><Icon name="swap-vert" size={20} color={colors.primary} /></Pressable></View>
        <PlaceField label="To" value={destination} onSelect={setDestination} />
        <View style={styles.row}><View style={{ flex: 1, gap: 5 }}><Text selectable style={[styles.label, { color: colors.onSurfaceVariant }]}>Departure</Text><TextInput value={departureAt} onChangeText={setDepartureAt} placeholder="YYYY-MM-DD" keyboardType="numbers-and-punctuation" style={[styles.dateInput, { color: colors.onSurface, borderColor: colors.outlineVariant }]} /></View>{!oneWay ? <View style={{ flex: 1, gap: 5 }}><Text selectable style={[styles.label, { color: colors.onSurfaceVariant }]}>Return</Text><TextInput value={returnAt} onChangeText={setReturnAt} placeholder="YYYY-MM-DD" keyboardType="numbers-and-punctuation" style={[styles.dateInput, { color: colors.onSurface, borderColor: colors.outlineVariant }]} /></View> : null}</View>
        <View style={styles.controls}><Pressable onPress={haptics.wrap('selection', () => setOneWay((current) => !current))} style={[styles.tripChoice, { backgroundColor: colors.surfaceContainerLow }]}><Icon name={oneWay ? 'radio-button-checked' : 'radio-button-unchecked'} size={19} color={colors.primary} /><Text selectable style={[styles.label, { color: colors.onSurface }]}>{oneWay ? 'One way' : 'Round trip'}</Text></Pressable><View style={styles.tripChoice}><Text selectable style={[styles.label, { color: colors.onSurface }]}>Non-stop only</Text><Switch value={direct} onValueChange={setDirect} /></View></View>
        <Pressable onPress={submit} style={({ pressed }) => [styles.searchButton, { backgroundColor: colors.primary }, pressed && { opacity: .9 }]}><Icon name="search" size={20} color={colors.onPrimary} /><Text selectable style={[styles.searchText, { color: colors.onPrimary }]}>Search flights</Text></Pressable>
      </View>
      {criteria ? <Text selectable style={[styles.disclaimer, { color: colors.textMuted }]}>Cached Aviasales price insights, not live ticket availability. Check the final price on the booking site.</Text> : null}
      {calendar.data?.days.length ? <View style={{ gap: Spacing.sm }}><Text selectable style={[styles.sectionTitle, { color: colors.onSurface }]}>Nearby dates</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: Spacing.sm }}>{calendar.data.days.slice(0, 7).map((day) => <View key={day.date} style={[styles.day, { backgroundColor: colors.surfaceContainerLow }]}><Text selectable style={[styles.dayDate, { color: colors.onSurfaceVariant }]}>{day.date.slice(5)}</Text><Text selectable style={[styles.dayPrice, { color: colors.onSurface }]}>{formatFare(day.price, calendar.data.currency)}</Text><Text selectable style={[styles.dayDate, { color: colors.textMuted }]}>{day.stops ? `${day.stops} stop${day.stops > 1 ? 's' : ''}` : 'Non-stop'}</Text></View>)}</ScrollView></View> : null}
      {search.isLoading ? <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text selectable style={{ color: colors.textMuted }}>Finding cached fares…</Text></View> : null}
      {error ? <View style={[styles.notice, { backgroundColor: colors.errorContainer }]}><Icon name="cloud-off" size={20} color={colors.error} /><Text selectable style={{ flex: 1, color: colors.error }}>{error}</Text></View> : null}
      {criteria && !search.isLoading && !error && offers.length === 0 ? <View style={[styles.notice, { backgroundColor: colors.surfaceContainerLow }]}><Icon name="flight" size={20} color={colors.onSurfaceVariant} /><Text selectable style={{ flex: 1, color: colors.onSurfaceVariant }}>No cached fares were found. Try nearby dates or another airport.</Text></View> : null}
      {offers.length ? <View style={{ gap: Spacing.sm }}><View style={[styles.row, { justifyContent: 'space-between' }]}><Text selectable style={[styles.sectionTitle, { color: colors.onSurface }]}>Best fares</Text><View style={styles.sorts}>{(['price', 'duration', 'stops'] as const).map((option) => <Pressable key={option} onPress={haptics.wrap('selection', () => setSort(option))} style={[styles.sort, { backgroundColor: sort === option ? colors.primary : colors.surfaceContainerLow }]}><Text selectable style={[styles.sortText, { color: sort === option ? colors.onPrimary : colors.onSurfaceVariant }]}>{option === 'price' ? 'Price' : option === 'duration' ? 'Fastest' : 'Stops'}</Text></Pressable>)}</View></View>{offers.map((offer, index) => <Pressable key={`${offer.airline}-${offer.flightNumber}-${index}`} onPress={() => setSelected(offer)} style={({ pressed }) => [styles.offer, { backgroundColor: colors.surfaceContainerLowest, borderColor: colors.outlineVariant }, pressed && { opacity: .9 }]}><View style={styles.row}><View style={[styles.logo, { backgroundColor: colors.surfaceContainerLow }]}>{airlineLogoUrl(offer.airline) ? <Image source={airlineLogoUrl(offer.airline)!} style={{ width: 62, height: 28 }} contentFit="contain" /> : <Icon name="flight" size={22} color={colors.primary} />}</View><View style={{ flex: 1, gap: 3 }}><Text selectable style={[styles.route, { color: colors.onSurface }]}>{offer.originAirport} <Text style={{ color: colors.primary }}>→</Text> {offer.destinationAirport}</Text><Text selectable style={{ ...Typography.bodySmall, color: colors.textMuted }}>{offer.airline ?? 'Airline'}{offer.flightNumber ? ` · ${offer.flightNumber}` : ''} · {offer.transfers ? `${offer.transfers} stop${offer.transfers > 1 ? 's' : ''}` : 'Non-stop'}</Text></View><Text selectable style={[styles.price, { color: colors.primary }]}>{formatFare(offer.price, search.data!.currency)}</Text></View><View style={[styles.row, { justifyContent: 'space-between' }]}><Text selectable style={{ ...Typography.bodySmall, color: colors.onSurfaceVariant }}>{formatFlightDateTime(offer.departureAt)}</Text><Text selectable style={{ ...Typography.bodySmall, color: colors.onSurfaceVariant }}>{formatFlightDuration(offer.duration)}</Text></View></Pressable>)}</View> : null}
    </ScrollView>
    <BottomSheet visible={!!selected} onClose={() => setSelected(null)} title="Flight details">{selected ? <View style={{ gap: Spacing.md }}><Text selectable style={[styles.route, { color: colors.onSurface }]}>{selected.originAirport} → {selected.destinationAirport}</Text><Text selectable style={{ color: colors.onSurfaceVariant }}>{selected.airline ?? 'Airline'}{selected.flightNumber ? ` · Flight ${selected.flightNumber}` : ''}</Text><Text selectable style={{ color: colors.onSurfaceVariant }}>Depart: {formatFlightDateTime(selected.departureAt)}{selected.returnAt ? `\nReturn: ${formatFlightDateTime(selected.returnAt)}` : ''}</Text><Text selectable style={{ color: colors.onSurfaceVariant }}>{formatFlightDuration(selected.duration)} · {selected.transfers ? `${selected.transfers} stop${selected.transfers > 1 ? 's' : ''}` : 'Non-stop'}</Text>{selected.expiresAt ? <Text selectable style={{ color: colors.textMuted }}>Cached price expires {formatFlightDateTime(selected.expiresAt)}.</Text> : null}<Pressable onPress={() => void openOffer(selected)} style={[styles.searchButton, { backgroundColor: colors.primary }]}><Icon name="open-in-new" size={19} color={colors.onPrimary} /><Text selectable style={[styles.searchText, { color: colors.onPrimary }]}>View on Aviasales</Text></Pressable></View> : null}</BottomSheet>
  </View>;
}

const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: Spacing.containerMargin, paddingBottom: 100, gap: Spacing.lg }, hero: { flexDirection: 'row', gap: Spacing.md, padding: Spacing.lg, borderRadius: Radius.xl, borderCurve: 'continuous' }, heroTitle: { ...Typography.headlineSm }, heroCopy: { ...Typography.bodySmall, lineHeight: 19 }, panel: { borderWidth: 1, padding: Spacing.md, gap: Spacing.md, borderRadius: Radius.xl, borderCurve: 'continuous' }, row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }, swap: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginVertical: -8 }, label: { ...Typography.labelMd, fontWeight: '600' }, dateInput: { borderWidth: 1, borderRadius: Radius.md, borderCurve: 'continuous', height: 46, paddingHorizontal: Spacing.sm, ...Typography.bodyMd }, controls: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm }, tripChoice: { flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 40, paddingHorizontal: Spacing.sm, borderRadius: Radius.md }, searchButton: { minHeight: 50, borderRadius: Radius.lg, borderCurve: 'continuous', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: Spacing.sm }, searchText: { ...Typography.labelMd, fontWeight: '700' }, disclaimer: { ...Typography.bodySmall, lineHeight: 18 }, sectionTitle: { ...Typography.headlineSm }, day: { width: 100, padding: Spacing.sm, gap: 3, borderRadius: Radius.lg, borderCurve: 'continuous' }, dayDate: { ...Typography.bodySmall }, dayPrice: { ...Typography.labelMd, fontWeight: '700' }, loading: { alignItems: 'center', padding: Spacing.xl, gap: Spacing.sm }, notice: { flexDirection: 'row', gap: Spacing.sm, padding: Spacing.md, borderRadius: Radius.lg, borderCurve: 'continuous' }, offer: { padding: Spacing.md, gap: Spacing.sm, borderWidth: 1, borderRadius: Radius.xl, borderCurve: 'continuous' }, logo: { width: 68, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.md }, route: { ...Typography.labelMd, fontWeight: '700' }, price: { ...Typography.labelMd, fontWeight: '800', fontVariant: ['tabular-nums'] }, sorts: { flexDirection: 'row', gap: 4 }, sort: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: Radius.full }, sortText: { ...Typography.bodySmall, fontWeight: '600' } });
