export {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signInWithCredential,
  signOut,
  sendPasswordResetEmail,
  updateProfile,
  onAuthStateChanged,
  linkWithCredential,
  PhoneAuthProvider,
  signInWithPhoneNumber,
  getIdToken,
  EmailAuthProvider,
  GoogleAuthProvider,
  AppleAuthProvider,
  reauthenticateWithCredential,
  updatePassword,
  deleteUser,
  getAdditionalUserInfo,
} from '@react-native-firebase/auth';
