#!/usr/bin/env python3
"""Generate white-on-transparent Android shortcut silhouettes from Material Icons.

PNG only — expo-quick-actions androidIcons does not accept SVG.
iOS uses SF Symbols via `symbol:` in home-screen-quick-actions.ts.

Usage: python scripts/generate-shortcut-icons.py
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SIZE = 432
FONT_SIZE = 240
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "images" / "shortcuts"
MI_FONT = ROOT / "node_modules/@react-native-vector-icons/material-icons/fonts/MaterialIcons.ttf"
MI_GLYPHS = (
    ROOT
    / "node_modules/@react-native-vector-icons/material-icons/glyphmaps/MaterialIcons.json"
)
FA_FONT = ROOT / "node_modules/@react-native-vector-icons/fontawesome6/fonts/FontAwesome6_Solid.ttf"
FA_GLYPHS = (
    ROOT
    / "node_modules/@react-native-vector-icons/fontawesome6/glyphmaps/FontAwesome6_solid.json"
)

# shortcut key → (family, glyph name). family: "mi" | "fa"
ICONS: dict[str, tuple[str, str]] = {
    "shortcut_verify": ("mi", "verified"),
    "shortcut_gem": ("mi", "diamond"),
    "shortcut_add": ("mi", "diamond"),
    "shortcut_ap": ("mi", "handshake"),
    "shortcut_cheque": ("fa", "money-check-dollar"),
    "shortcut_service": ("mi", "handyman"),
    "shortcut_jobs": ("mi", "construction"),
    "shortcut_contacts": ("mi", "contacts"),
    "shortcut_bill": ("mi", "receipt-long"),
    "shortcut_certificates": ("mi", "workspace-premium"),
    "shortcut_money": ("mi", "payments"),
    "shortcut_directory": ("mi", "storefront"),
    "shortcut_search": ("mi", "search"),
    "shortcut_news": ("mi", "newspaper"),
}


def render_glyph(font_path: Path, codepoint: int) -> Image.Image:
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    ch = chr(codepoint)
    bbox = draw.textbbox((0, 0), ch, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (SIZE - tw) / 2 - bbox[0]
    y = (SIZE - th) / 2 - bbox[1]
    draw.text((x, y), ch, font=font, fill=(255, 255, 255, 255))
    return img


def write_svg(name: str, family: str, glyph: str, codepoint: int) -> None:
    """Editable SVG stub documenting the icon glyph used for the PNG."""
    font_family = "Material Icons" if family == "mi" else "Font Awesome 6 Free"
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}">
  <!-- {font_family}: {glyph} (U+{codepoint:04X}) -->
  <!-- PNG generated by scripts/generate-shortcut-icons.py -->
  <text x="50%" y="54%" text-anchor="middle" dominant-baseline="middle"
        font-family="{font_family}" font-size="{FONT_SIZE}"
        fill="#FFFFFF">&#x{codepoint:04X};</text>
</svg>
"""
    (OUT / f"{name}.svg").write_text(svg, encoding="utf-8")


def main() -> None:
    if not MI_FONT.is_file():
        raise SystemExit(f"Missing Material Icons font: {MI_FONT}")
    mi: dict[str, int] = json.loads(MI_GLYPHS.read_text(encoding="utf-8"))
    fa: dict[str, int] = json.loads(FA_GLYPHS.read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (family, glyph) in ICONS.items():
        table = mi if family == "mi" else fa
        font = MI_FONT if family == "mi" else FA_FONT
        if glyph not in table:
            raise SystemExit(f"Unknown {family} glyph: {glyph}")
        codepoint = table[glyph]
        img = render_glyph(font, codepoint)
        img.save(OUT / f"{name}.png")
        write_svg(name, family, glyph, codepoint)
        print(f"wrote {name} <- {family}:{glyph}")


if __name__ == "__main__":
    main()
