#!/usr/bin/env python3
"""Generate theme-aware Android shortcut silhouettes from Material Icons.

PNG only — expo-quick-actions androidIcons does not accept SVG.
Produces transparent-background glyphs (no adaptive plate):
  *_light.png  → black (for light system theme)
  *_dark.png   → white (for dark system theme)

Register both as string icons in app.config.ts (string = non-adaptive).
JS picks light/dark via useColorScheme() in home-screen-quick-actions.ts.
iOS uses outline SF Symbols / built-ins (already theme-adaptive).

Usage: python scripts/generate-shortcut-icons.py
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SIZE = 432
# Render large, then crop to ink and scale to FILL of the canvas so icons
# use the full shortcut slot (fonts ship with their own glyph padding).
FONT_SIZE = 400
FILL = 0.92
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "images" / "shortcuts"
MI_FONT = ROOT / "node_modules/@react-native-vector-icons/material-icons/fonts/MaterialIcons.ttf"
MI_GLYPHS = (
    ROOT
    / "node_modules/@react-native-vector-icons/material-icons/glyphmaps/MaterialIcons.json"
)
FA_FONT = ROOT / "node_modules/@react-native-vector-icons/fontawesome6/fonts/FontAwesome6_Solid.ttf"
FA_GLYPHS = (
    ROOT
    / "node_modules/@react-native-vector-icons/fontawesome6/glyphmaps/FontAwesome6_solid.json"
)

# shortcut key → (family, glyph name). family: "mi" | "fa"
ICONS: dict[str, tuple[str, str]] = {
    "shortcut_gem": ("mi", "diamond"),
    "shortcut_add": ("mi", "diamond"),
    "shortcut_ap": ("mi", "handshake"),
    "shortcut_cheque": ("fa", "money-check-dollar"),
    "shortcut_service": ("mi", "handyman"),
    "shortcut_jobs": ("mi", "construction"),
    "shortcut_contacts": ("mi", "contacts"),
    "shortcut_bill": ("mi", "receipt-long"),
    "shortcut_money": ("mi", "payments"),
    "shortcut_market": ("mi", "storefront"),
    "shortcut_search": ("mi", "search"),
}

# light theme menu → black glyph; dark theme menu → white glyph
THEMES: dict[str, tuple[int, int, int, int]] = {
    "light": (0, 0, 0, 255),
    "dark": (255, 255, 255, 255),
}


def render_glyph(
    font_path: Path, codepoint: int, fill: tuple[int, int, int, int]
) -> Image.Image:
    # Oversized canvas so large glyphs are never clipped before crop/scale.
    pad = SIZE * 2
    raw = Image.new("RGBA", (pad, pad), (0, 0, 0, 0))
    draw = ImageDraw.Draw(raw)
    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    ch = chr(codepoint)
    bbox = draw.textbbox((0, 0), ch, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (pad - tw) / 2 - bbox[0]
    y = (pad - th) / 2 - bbox[1]
    draw.text((x, y), ch, font=font, fill=fill)

    ink = raw.getbbox()
    if ink is None:
        return Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    cropped = raw.crop(ink)
    target = max(1, int(SIZE * FILL))
    scale = target / max(cropped.width, cropped.height)
    new_w = max(1, int(round(cropped.width * scale)))
    new_h = max(1, int(round(cropped.height * scale)))
    scaled = cropped.resize((new_w, new_h), Image.Resampling.LANCZOS)

    out = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    out.paste(scaled, ((SIZE - new_w) // 2, (SIZE - new_h) // 2), scaled)
    return out


def write_svg(name: str, family: str, glyph: str, codepoint: int) -> None:
    """Editable SVG stub documenting the icon glyph used for the PNG."""
    font_family = "Material Icons" if family == "mi" else "Font Awesome 6 Free"
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}">
  <!-- {font_family}: {glyph} (U+{codepoint:04X}) -->
  <!-- PNG generated by scripts/generate-shortcut-icons.py (*_light / *_dark) -->
  <text x="50%" y="54%" text-anchor="middle" dominant-baseline="middle"
        font-family="{font_family}" font-size="{FONT_SIZE}"
        fill="#000000">&#x{codepoint:04X};</text>
</svg>
"""
    (OUT / f"{name}.svg").write_text(svg, encoding="utf-8")


def main() -> None:
    if not MI_FONT.is_file():
        raise SystemExit(f"Missing Material Icons font: {MI_FONT}")
    mi: dict[str, int] = json.loads(MI_GLYPHS.read_text(encoding="utf-8"))
    fa: dict[str, int] = json.loads(FA_GLYPHS.read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (family, glyph) in ICONS.items():
        table = mi if family == "mi" else fa
        font = MI_FONT if family == "mi" else FA_FONT
        if glyph not in table:
            raise SystemExit(f"Unknown {family} glyph: {glyph}")
        codepoint = table[glyph]
        for theme, fill in THEMES.items():
            img = render_glyph(font, codepoint, fill)
            out_name = f"{name}_{theme}"
            img.save(OUT / f"{out_name}.png")
            print(f"wrote {out_name} <- {family}:{glyph}")
        write_svg(name, family, glyph, codepoint)
        # Remove legacy unthemed PNG if present (was white-only).
        legacy = OUT / f"{name}.png"
        if legacy.is_file():
            legacy.unlink()


if __name__ == "__main__":
    main()
